name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-check-typescript:
    name: Build, check, and test the TypeScript Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Get npm cache directory
        id: npm-cache-directory
        run: |
          echo "directory=$(nix develop --command npm config get cache | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Set up npm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-directory.outputs.directory }}
          key: flakehub-mirror-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            flakehub-mirror-npm-cache

      - name: Install npm dependencies
        run: nix develop --command npm ci
      - name: Check prettier formatting
        run: nix develop --command npm run format
      - name: Run ESLint
        run: nix develop --command npm run lint
      - name: Run Vitest test suite
        run: nix develop --command npm run test
      - name: Build using tsup
        run: nix develop --command npm run build
      - name: Package using ncc
        run: nix develop --command npm run package
      - name: git status
        run: git status --porcelain=v1
      - name: Ensure no unstaged changes
        run: git diff --exit-code
