on:
  workflow_dispatch:
  push:
  
jobs:
  example_matrix:
    strategy:
      matrix:
        repo: [NixOS/nix]
    runs-on: ubuntu-latest
    permissions:
      contents: write # In order to upload artifacts to GitHub releases
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - uses: DeterminateSystems/nix-installer-action@v3
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ matrix.repo }}
        id: tagfetch

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ steps.tagfetch.outputs.tag }}

      - name: Release to Nxfr
        uses: DeterminateSystems/nxfr-push@main
        with:
          visibility: public
          mirrored-for: ${{ matrix.repo }}
          mirrored-tag: ${{ steps.tagfetch.outputs.tag }}
