on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '30 5,17 * * *'
  
jobs:
  mirror_tags:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - NixOS/nix
          - nix-community/disko
          - nix-community/lanzaboote
          - nix-community/harmonia
          - nix-community/haumea
          - nix-community/lorri
          - nix-community/nix-direnv
          - nix-community/nix-eval-jobs
          - nix-community/nix-index
          - nix-community/nix-init
          - nix-community/nix-melt
          - nix-community/nix-zsh-completions
          - nix-community/nixd
          - nix-community/nixpkgs-fmt
          - nix-community/nurl
          - nix-community/poetry2nix
          - Mic92/nix-update
          - Mic92/nixos-shell
          - Mic92/nixpkgs-review
          - Mic92/ssh-to-age
          - astro/deadnix
          - astro/microvm.nix
          - figsoda/utf8
          - hyprwm/Hyprland
          - kamadorueda/alejandra
          - kamadorueda/nixel
          - nerdypepper/statix
          - ryantm/agenix
          - serokell/nixfmt
          - vlinkz/nix-software-center
          - zhaofengli/colmena
    runs-on: ubuntu-latest
    permissions:
      contents: write # In order to upload artifacts to GitHub releases
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ matrix.repo }}
        id: tagfetch

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ steps.tagfetch.outputs.tag }}

      - name: Release to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          mirror: true
          visibility: public
          repository: ${{ matrix.repo }}
          tag: ${{ steps.tagfetch.outputs.tag }}
          log-directives: flakehub_push=trace
          logger: pretty
          flakehub-push-pr: 25
          
  rolling:
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: NixOS/nixpkgs
            branch: nixos-unstable
            rolling-prefix: v0.1
          - repo: NixOS/nixpkgs
            branch: nixos-22.11
            rolling-prefix: v22.11
          - repo: NixOS/nixpkgs
            branch: nixos-23.05
            rolling-prefix: v23.5
          - repo: nix-community/home-manager
            branch: master
            rolling-prefix: v0.1
          - repo: nix-community/nixos-generators
            branch: master
            rolling-prefix: v0.1
          - repo: NixOS/nixos-hardware
            branch: master
            rolling-prefix: v0.1
          - repo: nix-community/dream2nix
            branch: main
            rolling-prefix: v0.1
          - repo: cole-h/nixos-config
            branch: darwin
            rolling-prefix: v0.1
          - repo: DeterminateSystems/nix-netboot-serve
            branch: main
            rolling-prefix: v0.1
          - repo: nixified-ai/flake
            branch: master
            rolling-prefix: v0.1
          - repo: numtide/flake-utils
            branch: main
            rolling-prefix: v0.1
          - repo: ryantm/nixpkgs-update
            branch: main
            rolling-prefix: v0.1
          - repo: nix-community/fenix
            branch: main
            rolling-prefix: v0.1
          - repo: zhaofengli/attic
            branch: main
            rolling-prefix: v0.1
          - repo: Mic92/sops-nix
            branch: master
            rolling-prefix: v0.1
          - repo: nix-community/impermanence
            branch: master
            rolling-prefix: v0.1
          - repo: nix-community/naersk
            branch: master
            rolling-prefix: v0.1
          - repo: Gerschtli/nix-formatter-pack
            branch: master
            rolling-prefix: v0.1
    runs-on: ubuntu-latest
    permissions:
      contents: write # In order to upload artifacts to GitHub releases
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.branch }}

      - name: Release to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          mirror: true
          visibility: public
          repository: ${{ matrix.repo }}
          rolling-prefix: ${{ matrix.rolling-prefix }}
          log-directives: flakehub_push=trace
          logger: pretty
          flakehub-push-pr: 25
