on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '30 5,17 * * *'
  
jobs:
  mirror_tags:
    strategy:
      fail-fast: false
      matrix:
        repo:
          - NixOS/nix
          - nix-community/disko
          - nix-community/lanzaboote
          - nix-community/nix-eval-jobs
          - figsoda/utf8
    runs-on: ubuntu-latest
    permissions:
      contents: write # In order to upload artifacts to GitHub releases
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ matrix.repo }}
        id: tagfetch

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ steps.tagfetch.outputs.tag }}

      - name: Release to Nxfr
        uses: DeterminateSystems/flakehub-push@main
        with:
          mirror: true
          visibility: public
          repository: ${{ matrix.repo }}
          tag: ${{ steps.tagfetch.outputs.tag }}
          log-directives: flakehub_push=trace
          logger: pretty
          flakehub-push-pr: 25
          
  rolling:
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: NixOS/nixpkgs
            branch: nixos-unstable
            rolling-prefix: v0.1
          - repo: NixOS/nixpkgs
            branch: nixos-22.11
            rolling-prefix: v22.11
          - repo: NixOS/nixpkgs
            branch: nixos-23.05
            rolling-prefix: v23.5
          - repo: nix-community/home-manager
            branch: master
            rolling-prefix: v0.1
          - repo: nix-community/nixos-generators
            branch: master
            rolling-prefix: v0.1
          - repo: nix-community/dream2nix
            branch: main
            rolling-prefix: v0.1
          - repo: cachix/nixpkgs-python
            branch: main
            rolling-prefix: v0.1
          - repo: nix-community/poetry2nix
            branch: main
            rolling-prefix: v0.1
            
    runs-on: ubuntu-latest
    permissions:
      contents: write # In order to upload artifacts to GitHub releases
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.branch }}

      - name: Release to Nxfr
        uses: DeterminateSystems/flakehub-push@tidy-up-for-nxfr-mirror
        with:
          mirror: true
          visibility: public
          repository: ${{ matrix.repo }}
          rolling-prefix: ${{ matrix.rolling-prefix }}
          log-directives: flakehub_push=trace
          logger: pretty
          flakehub-push-pr: 25
