name: "Publish every Git push to NixOS release branches to FlakeHub. nixos-unstable is 0.1.x, and nixos-yy.mm is 0.yymm.x."
run-name: Mirror Nixpkgs ${{ inputs.release-branch }}
on:
  workflow_dispatch:
    inputs:
      release-branch:
        description: "The release branch to publish to FlakeHub"
        type: "string"
        required: true

jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Determine minor version
        id: minor-version
        run: node "$GITHUB_ACTION_PATH/dist/index.js"

      - uses: "actions/checkout@v3"
        if: steps.minor-version.outputs.minorVersion
        with:
          repository: "NixOS/nixpkgs"
          ref: ${{ inputs.release-branch }}

      - uses: "DeterminateSystems/nix-installer-action@main"
        if: steps.minor-version.outputs.minorVersion

      - uses: DeterminateSystems/magic-nix-cache-action@main
        if: steps.minor-version.outputs.minorVersion

      - uses: "DeterminateSystems/flakehub-push@main"
        if: steps.minor-version.outputs.minorVersion
        with:
          name: "NixOS/nixpkgs"
          repository: "NixOS/nixpkgs"
          rolling: true
          visibility: "public"
          rolling-minor: "${{ steps.minor-version.outputs.minorVersion }}"
          mirror: true
          log-directives: flakehub_push=trace
          logger: pretty
