name: "Mirror a repo's latest commit to a specific branch to FlakeHub."
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to publish."
        type: "string"
        required: true
      repo:
        description: "The repo to publish, in the format of Owner/Repo."
        type: "string"
        required: true
      rolling_minor:
        description: "The minor version to publish under."
        type: "string"
        required: true
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v3"
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
        
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/magic-nix-cache-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          mirror: true
          visibility: public
          repository: ${{ inputs.repo }}
          rolling: true
          rolling-minor: ${{ fromJSON(inputs.rolling_minor) }}
          log-directives: flakehub_push=trace
          logger: pretty
